"C:\Program Files\Inkscape\inkscape.exe" -z "D:\svg_conversion\test_steps_case_9.svg" -e test_steps_case_9.png
"C:\Program Files\Inkscape\inkscape.exe" -z "D:\svg_conversion\test_steps_case_8.svg" -e test_steps_case_8.png
"C:\Program Files\Inkscape\inkscape.exe" -z "D:\svg_conversion\test_steps_case_7_overage.svg" -e test_steps_case_7_overage.png
"C:\Program Files\Inkscape\inkscape.exe" -z "D:\svg_conversion\test_steps_case_7.svg" -e test_steps_case_7.png
"C:\Program Files\Inkscape\inkscape.exe" -z "D:\svg_conversion\test_steps_case_6-2.svg" -e test_steps_case_6-2.png
"C:\Program Files\Inkscape\inkscape.exe" -z "D:\svg_conversion\test_steps_case_6.svg" -e test_steps_case_6.png
"C:\Program Files\Inkscape\inkscape.exe" -z "D:\svg_conversion\test_steps_case_4_nextbilling_cycle.svg" -e test_steps_case_4_nextbilling_cycle.png
"C:\Program Files\Inkscape\inkscape.exe" -z "D:\svg_conversion\test_steps_case_4.svg" -e test_steps_case_4.png
"C:\Program Files\Inkscape\inkscape.exe" -z "D:\svg_conversion\test_steps_case_34.svg" -e test_steps_case_34.png
"C:\Program Files\Inkscape\inkscape.exe" -z "D:\svg_conversion\test_steps_case_33.svg" -e test_steps_case_33.png
"C:\Program Files\Inkscape\inkscape.exe" -z "D:\svg_conversion\test_steps_case_32.svg" -e test_steps_case_32.png
"C:\Program Files\Inkscape\inkscape.exe" -z "D:\svg_conversion\test_steps_case_3.svg" -e test_steps_case_3.png
"C:\Program Files\Inkscape\inkscape.exe" -z "D:\svg_conversion\test_steps_case_2.svg" -e test_steps_case_2.png
"C:\Program Files\Inkscape\inkscape.exe" -z "D:\svg_conversion\test_steps_case_18.svg" -e test_steps_case_18.png
"C:\Program Files\Inkscape\inkscape.exe" -z "D:\svg_conversion\test_steps_case_14.svg" -e test_steps_case_14.png
"C:\Program Files\Inkscape\inkscape.exe" -z "D:\svg_conversion\test_steps_case_13_2.svg" -e test_steps_case_13_2.png
"C:\Program Files\Inkscape\inkscape.exe" -z "D:\svg_conversion\test_steps_case_13_1.svg" -e test_steps_case_13_1.png
"C:\Program Files\Inkscape\inkscape.exe" -z "D:\svg_conversion\test_steps_case_12.svg" -e test_steps_case_12.png
"C:\Program Files\Inkscape\inkscape.exe" -z "D:\svg_conversion\test_steps_case_11.svg" -e test_steps_case_11.png
"C:\Program Files\Inkscape\inkscape.exe" -z "D:\svg_conversion\test_steps_case_10.svg" -e test_steps_case_10.png
"C:\Program Files\Inkscape\inkscape.exe" -z "D:\svg_conversion\test_steps_case_1.svg" -e test_steps_case_1.png